/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Services.Thrift.DataTransfer;
using Thrift;
using Thrift.Collections;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

public static class pr1Extensions
{
  public static bool Equals(this List<GameDto> instance, object that)
  {
    if (!(that is List<GameDto> other)) return false;
    if (ReferenceEquals(instance, other)) return true;

    return TCollections.Equals(instance, other);
  }


  public static int GetHashCode(this List<GameDto> instance)
  {
    return TCollections.GetHashCode(instance);
  }


  public static List<GameDto> DeepCopy(this List<GameDto> source)
  {
    if (source == null)
      return null;

    var tmp34 = new List<GameDto>(source.Count);
    foreach (var elem in source)
      tmp34.Add((elem != null) ? elem.DeepCopy() : null);
    return tmp34;
  }


}
